"""phase_7_ai_employee

Revision ID: 5e1efd1feee9
Revises: f1f5d7fe24f4
Create Date: 2026-09-04 04:47:13.025885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1efd1feee9'
down_revision: Union[str, Sequence[str], None] = 'f1f5d7fe24f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'ai_employees' not in existing_tables:
        op.create_table(
            'ai_employees',
            sa.Column('id', sa.String(length=36), primary_key=True),
            sa.Column('organization_id', sa.String(length=36), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, index=True),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.Column('role', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('status', sa.String(length=50), default='ACTIVE', nullable=False),
            sa.Column('permissions', sa.JSON(), nullable=False),
            sa.Column('configuration', sa.JSON(), nullable=False),
            sa.Column('llm_provider', sa.String(length=50), default='deterministic', nullable=False),
            sa.Column('llm_model', sa.String(length=100), default='gpt-4o-mini', nullable=False),
            sa.Column('max_steps', sa.Integer(), default=12, nullable=False),
            sa.Column('max_replans', sa.Integer(), default=3, nullable=False),
            sa.Column('timeout_seconds', sa.Integer(), default=120, nullable=False),
            sa.Column('confidence_threshold_auto', sa.Float(), default=0.90, nullable=False),
            sa.Column('confidence_threshold_review', sa.Float(), default=0.70, nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(), nullable=True),
        )

    if 'agent_steps' not in existing_tables:
        op.create_table(
            'agent_steps',
            sa.Column('id', sa.String(length=36), primary_key=True),
            sa.Column('agent_run_id', sa.String(length=36), sa.ForeignKey('agent_runs.id', ondelete='CASCADE'), nullable=False, index=True),
            sa.Column('organization_id', sa.String(length=36), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, index=True),
            sa.Column('step_index', sa.Integer(), nullable=False),
            sa.Column('step_type', sa.String(length=100), nullable=False),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('input_data', sa.JSON(), nullable=False),
            sa.Column('output_data', sa.JSON(), nullable=False),
            sa.Column('started_at', sa.DateTime(), nullable=False),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('duration_ms', sa.Integer(), nullable=True),
            sa.Column('error', sa.Text(), nullable=True),
            sa.Column('step_metadata', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('deleted_at', sa.DateTime(), nullable=True),
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_employee_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trigger_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trigger_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('actor_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('actor_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('context_data', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('extracted_data', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('decisions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('policy_results', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('planned_actions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('completed_actions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('intent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('intent_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('decision_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reason_codes', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('evidence_ids', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('requires_human_approval', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('approval_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failure_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('failure_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('errors', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_used', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_steps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('replan_count', sa.Integer(), nullable=False))
        batch_op.alter_column('agent_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_agent_runs_ai_employee_id'), ['ai_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_agent_runs_ai_employee_id', 'ai_employees', ['ai_employee_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_agent_runs_agent_id', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agent_runs_agent_id_old', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_ai_employee_id'))
        batch_op.alter_column('agent_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('replan_count')
        batch_op.drop_column('total_steps')
        batch_op.drop_column('model_used')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')
        batch_op.drop_column('errors')
        batch_op.drop_column('failure_summary')
        batch_op.drop_column('failure_code')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_id')
        batch_op.drop_column('requires_human_approval')
        batch_op.drop_column('evidence_ids')
        batch_op.drop_column('reason_codes')
        batch_op.drop_column('decision_summary')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('intent_confidence')
        batch_op.drop_column('intent')
        batch_op.drop_column('completed_actions')
        batch_op.drop_column('planned_actions')
        batch_op.drop_column('policy_results')
        batch_op.drop_column('decisions')
        batch_op.drop_column('extracted_data')
        batch_op.drop_column('context_data')
        batch_op.drop_column('current_step')
        batch_op.drop_column('actor_id')
        batch_op.drop_column('actor_type')
        batch_op.drop_column('trigger_id')
        batch_op.drop_column('trigger_type')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('ai_employee_id')

    # ### end Alembic commands ###
