"""phase_8_tool_registry

Revision ID: 785a8c89f7e2
Revises: 5e1efd1feee9
Create Date: 2026-09-04 05:51:09.686281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785a8c89f7e2'
down_revision: Union[str, Sequence[str], None] = '5e1efd1feee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_version', sa.String(length=20), nullable=False, server_default='v1'))
        batch_op.add_column(sa.Column('requested_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('requested_by_type', sa.String(length=50), nullable=False, server_default='AI_AGENT'))
        batch_op.add_column(sa.Column('approved_by_user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('validated_input', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('execution_receipt', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('permission_granted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('policy_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('approval_required', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('approval_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approval_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('block_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_mode', sa.String(length=20), nullable=False, server_default='LIVE_MOCK'))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_tool_executions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_status'), ['status'], unique=False)

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='READ'))
        batch_op.add_column(sa.Column('required_permissions', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('approval_mode', sa.String(length=20), nullable=False, server_default='NEVER'))
        batch_op.add_column(sa.Column('handler_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=20), nullable=False, server_default='v1'))
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('failure_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_tools_category'), ['category'], unique=False)

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_category'))
        batch_op.alter_column('description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('failure_count')
        batch_op.drop_column('max_retries')
        batch_op.drop_column('timeout_seconds')
        batch_op.drop_column('version')
        batch_op.drop_column('handler_key')
        batch_op.drop_column('approval_mode')
        batch_op.drop_column('required_permissions')
        batch_op.drop_column('category')
        batch_op.drop_column('display_name')

    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_status'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_idempotency_key'))
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('execution_mode')
        batch_op.drop_column('block_reason')
        batch_op.drop_column('error_code')
        batch_op.drop_column('approval_hash')
        batch_op.drop_column('approval_id')
        batch_op.drop_column('approval_required')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('policy_decision')
        batch_op.drop_column('permission_granted')
        batch_op.drop_column('execution_receipt')
        batch_op.drop_column('validated_input')
        batch_op.drop_column('approved_by_user_id')
        batch_op.drop_column('requested_by_type')
        batch_op.drop_column('requested_by')
        batch_op.drop_column('tool_version')

    # ### end Alembic commands ###
