"""phase_5_ingestion_layer

Revision ID: f1f5d7fe24f4
Revises: ffd4068f43da
Create Date: 2026-09-04 03:47:57.629061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f5d7fe24f4'
down_revision: Union[str, Sequence[str], None] = 'ffd4068f43da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('successful_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_report', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=255), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('source_uri', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('source_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('security_classification', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('security_flags', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thread_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recipients', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('bcc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('body_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachments_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('source_account', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('classification_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('security_classification', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('security_flags', sa.JSON(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))
        batch_op.create_index(batch_op.f('ix_emails_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_external_message_id'), ['external_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_thread_id'), ['thread_id'], unique=False)
        batch_op.drop_column('body')
        batch_op.drop_column('message_id')

    with op.batch_alter_table('website_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('raw_content_reference', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('crawl_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('security_classification', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('security_flags', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_domains', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('respect_robots_txt', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('max_depth', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_pages', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_column('max_pages')
        batch_op.drop_column('max_depth')
        batch_op.drop_column('respect_robots_txt')
        batch_op.drop_column('allowed_domains')

    with op.batch_alter_table('website_pages', schema=None) as batch_op:
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('security_flags')
        batch_op.drop_column('security_classification')
        batch_op.drop_column('crawl_status')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('language')
        batch_op.drop_column('content_type')
        batch_op.drop_column('raw_content_reference')
        batch_op.drop_column('canonical_url')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_emails_thread_id'))
        batch_op.drop_index(batch_op.f('ix_emails_external_message_id'))
        batch_op.drop_index(batch_op.f('ix_emails_content_hash'))
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=False)
        batch_op.drop_column('security_flags')
        batch_op.drop_column('security_classification')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('classification_status')
        batch_op.drop_column('source_account')
        batch_op.drop_column('source')
        batch_op.drop_column('attachments_count')
        batch_op.drop_column('body_html')
        batch_op.drop_column('body_text')
        batch_op.drop_column('bcc')
        batch_op.drop_column('recipients')
        batch_op.drop_column('thread_id')
        batch_op.drop_column('external_message_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('processed_at')
        batch_op.drop_column('security_flags')
        batch_op.drop_column('security_classification')
        batch_op.drop_column('source_hash')
        batch_op.drop_column('source_uri')
        batch_op.drop_column('source_type')
        batch_op.drop_column('storage_key')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_column('section')
        batch_op.drop_column('page_number')

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_created_at'))

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
